---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.npm
    - node_modules

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

script:
  - npm run lint:js
  - npm run build -- --environment=production

